name: tunio_radio_player
description: "A Flutter radio streaming application with auto-start functionality"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.4
  shared_preferences: ^2.3.3
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  audio_session: ^0.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  # Optional: adaptive icon for Android
  adaptive_icon_background: "#1A131F"
  #adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
