name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter version
      run: flutter --version
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Setup Android signing
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=upload-keystore.jks" >> android/key.properties
        
    - name: Build Android App Bundle
      run: flutter build appbundle --release
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload Android artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-builds
        path: |
          build/app/outputs/bundle/release/app-release.aab
          build/app/outputs/flutter-apk/app-release.apk
          
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Flutter version
      run: flutter --version
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Enable macOS desktop
      run: flutter config --enable-macos-desktop
      
    - name: Build macOS app
      run: flutter build macos --release
      
    - name: Create macOS archive
      run: |
        cd build/macos/Build/Products/Release
        tar -czf tunio-player-macos.tar.gz tunio_radio_player.app
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-builds
        path: build/macos/Build/Products/Release/tunio-player-macos.tar.gz
        
  create-release:
    name: Create Release
    needs: [build-android, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Download Android artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-builds
        path: ./android-builds
        
    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-builds
        path: ./macos-builds
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Что нового в версии ${{ steps.get_version.outputs.VERSION }}
          
          ### Файлы для скачивания:
          - **app-release.aab** - Android App Bundle для загрузки в Google Play
          - **app-release.apk** - APK файл для тестирования на Android
          - **tunio-player-macos.tar.gz** - macOS приложение
          
          ### Инструкции по установке:
          
          #### Android:
          - Для обычной установки: скачайте APK и установите
          - Для публикации в Google Play: используйте AAB файл
          
          #### macOS:
          - Распакуйте архив и перенесите приложение в папку Applications
          
          ---
          
          Проект автоматически собран через GitHub Actions
        files: |
          ./android-builds/app-release.aab
          ./android-builds/app-release.apk
          ./macos-builds/tunio-player-macos.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 